### ISSUE TITLE
What every dimensions mean in constructor params type?

### ISSUE THREAD

**Issue by Kayxue** [favna/discordjs-docs-parser#139]
What every dimensions mean in constructor params type?
I didn't found that you write about this in docs
```
[ [ [ 'ClientOptions' ] ] ]
```

**Comment by favna** [comment]
Nothing in particular really, it's just how it is parsed from the source JSON file. You can see how for Spinel and the DiscordJS Utils bot it is simply flattened: https://github.com/sapphiredev/spinel/blob/main/src/lib/util/discordjs-docs.ts and https://github.com/discordjs/discord-utils-bot/blob/main/src/functions/docs.ts
